### ISSUE TITLE
词法分析器的算符部分

### ISSUE THREAD

**Issue by hanliutong** [hanliutong/compiler#1]
# 开始进行词法分析器的算符部分开发
预计涉及到的文件: /lex/lex.cpp
分工调整，Assign给王时予 @WDDcat

**Comment by WDDcat** [comment]
Done.

**Comment by hanliutong** [comment]
我做语法分析的时候发现多了 { } 两个算符，需要添加对应的状态和接口定义 @WDDcat @bjutfgxqzn

**Comment by WDDcat** [comment]
我之前还在想为甚么没有打括号，我以为有then就不用了

**Comment by WDDcat** [comment]
Done.
