### ISSUE TITLE
词法/语法分析器 接口标准讨论

### ISSUE THREAD

**Issue by bjutfgxqzn** [hanliutong/compiler#2]
# 2 词法分析器 返回单词种别（整数表示）
# 3 词法分析器 返回单词属性（不同属性对应不同全局变量） @hanliutong @WDDcat @Jakob1357

**Comment by hanliutong** [comment]
## 返回值INT 

表示种别：需要定义各个种别的整型值
`int scan(char* input)`
## 全部变量 

表示单词属性：需要定义全局变量存储单词属性

## 例子

| 种别 | 属性 |
| - | -|
| INT10 | 0 |
| INT10 | 92 |
| + | _ |
| IDN | data |
| > | _ |
| INT16 | 63 |
| INT8 | 0 |
| WHILE |_|

**Comment by bjutfgxqzn** [comment]
徐老师关于此问题的回复：在实验题目的测试数据示例中，运算符（+,>),关键词（while）都没有属性（属性为无）。这样定义是可以的，但更鼓励进行实验时由后续语法分析的需要来重新定义单词种别及属性。

**Comment by hanliutong** [comment]
@Jakob1357 语法分析中对词法分析器的种别和属性的需求大概是？

**Comment by Jakob1357** [comment]
@hanliutong 目前来看，我觉得需要的属性有三类数字，返回的是三种int型的值；标识符，返回一个类。感觉关键字和+，-这样的关键字和运算符暂时可以无属性。如果行不通可以再讨论。

**Comment by bjutfgxqzn** [comment]
@Jakob1357 标识符返回的是它本身吗？比如说上面韩柳彤发的例子中输入数据"data"的属性就为data。

**Comment by Jakob1357** [comment]
@bjutfgxqzn 你是说返回的是个字符串吗？

**Comment by bjutfgxqzn** [comment]
@Jakob1357 是的

**Comment by WDDcat** [comment]
我在想有没有必要以宏定义的形式把接口返回的种别单独定义在一个头文件里 @bjutfgxqzn @hanliutong

**Comment by hanliutong** [comment]
类似于`#define INT10 10`？我感觉好像确实会优雅一点 @WDDcat

**Comment by WDDcat** [comment]
对对对，这样代码可读性也强一些 @hanliutong

**Comment by hanliutong** [comment]
`int NUM = 0; `INT8 INT10 INT16属性的全局变量

`string IDN_NAME;` 标识符属性的全局变量

[宏定义](../blob/master/lex/define.h)
