### ISSUE TITLE
词法分析器的KeyWord分析部分

### ISSUE THREAD

**Issue by hanliutong** [hanliutong/compiler#3]
# 王时予 @WDDcat 
按照状态图增加状态机的状态，完成词法分析器对关键词的分析

**Comment by WDDcat** [comment]
都需要哪些关键词，有要求么？

**Comment by hanliutong** [comment]
@WDDcat 见[实验要求](https://github.com/hanliutong/compiler/tree/master/Reference)

**Comment by hanliutong** [comment]
我看了一下，keyWord部分和之前的标识符部分有耦合，我来负责KeyWord吧。 @WDDcat 做算符的部分？

**Comment by hanliutong** [comment]
Done
