### ISSUE TITLE
没有input += index; 导致死循环

### ISSUE THREAD

**Issue by hanliutong** [hanliutong/compiler#5]
在所有`return 种别`之前都没有指针后移语句`input += index;`

我已经将导致错误的commit回滚了，当前commit是 @bjutfgxqzn 修改前的版本，请重新修改以解决bug

@bjutfgxqzn 本次及以后的代码提交请遵循以下顺序

1. 从本库fork一个库到你的github
2. 在自己fork出的库中进行commit push等操作
3. 在github中对自己的库提交merge request到本库的请求，并assign @hanliutong 进行code review

**Comment by bjutfgxqzn** [comment]
bug fixed
